# BFI & Recharge Calculations

# Initialize Packages
```{r, warning=FALSE}
here::i_am("code/BFI-calculations.Rmd")

# Initialize packages
packages <- c("tidyverse", "caret", "ggplot2", "modelr", "boot", "here", "sf", "raster", "prism", "exactextractr", "devtools")

# Install packages not yet installed
installed_packages <- packages %in% rownames(installed.packages())
if (any(installed_packages == FALSE)) {
  install.packages(packages[!installed_packages])
}

# Load packages
invisible(lapply(packages, library, character.only = TRUE))

set.seed(313)
```

## BFI Prediction of Basins

```{r}
# Access BFI.predictor function
source("BFI-predict-function.R")

# Load in dataset of points on every stream reach
PredictorPoints <- read_csv(here("data/GWBasins_PredictorPoints.csv"))
Points_LatLong <- PredictorPoints[,2:3]

# Divide the dataset into 10 equal sets
num_sets <- 10
set_size <- nrow(Points_LatLong) / num_sets
point_sets <- split(Points_LatLong, cut(seq_along(Points_LatLong$LAT), breaks = num_sets, labels = FALSE))

# Initialize an empty list to store the results
results_list <- list()

# Loop over each set and run BFI.predictor
for (i in 1:num_sets) {
  
  start.time <- Sys.time()
  #Model derived from code/XGB-training-testing
  point_annualBFI <- BFI.predictor(input_dataframe = point_sets[[i]], model_path = xgb.model)
  
  end.time <- Sys.time()
  time.taken <- round(end.time - start.time,2)
  cat("Finished set", i, "of", num_sets)
  
  results_list[[i]] <- point_annualBFI
}

#Create dataframe from list of dataframes
results <- data.table::rbindlist(results_list)

#write_csv(results, here("results/PredictingPoints_AllData.csv"))
```

## Calculate Recharge by HUC

```{r}
PredictingPoints <- read_csv(here("results/PredictingPoints_AllData.csv"))
point_BFI <- PredictingPoints[,c(1:5,10,51)]

point_BFI <- point_BFI %>%
  mutate(Recharge = predictedBFI * (PRECIP_MM - ET_MM))

# Calculate mean annual recharge for each HUC and each year
mean_recharge <- point_BFI %>%
  group_by(GWBasin, YEAR) %>%
  summarise(mean_recharge = mean(Recharge, na.rm = TRUE))

mean_recharge$mean_recharge <- ifelse(mean_recharge$mean_recharge < 0, 0, mean_recharge$mean_recharge)

mean_annual <- mean_recharge %>%
  group_by(GWBasin) %>%
  summarise(recharge_mm = mean(mean_recharge))

mean_annual$recharge_mm <- ifelse(mean_annual$recharge_mm < 0, 0, mean_annual$recharge_mm)

write_csv(mean_annual, here("results/GWBasin_Recharge_MEAN.nonzeroed.csv"))
```
